image: Visual Studio 2019

# Download script file from GitHub
init:
  - ps: |
      $ErrorActionPreference = "Stop"
      Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
      Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - git submodule update --init --recursive

environment:
  app_version: "1.3"
  USE_RTOOLS: true
  NOT_CRAN: true
  KEEP_VIGNETTES: true
  R_ARCH: x64
  R_VERSION: "4.2.0"
  COVERALLS_TOKEN:
     secure: oalu+A24LCfXr0AU0xQ/doYNZ5Z9EJ4Iy3y7MfS/Gbp2gN6LSrTUtIxo0eBLeHMk

version: "$(app_version).{build}"

before_build:
  - rake "prepare_for_build[%APPVEYOR_BUILD_VERSION%]"

build_script:
  - Rscript -e "install.packages(c('R6', 'stringr', 'readr', 'readxl', 'shiny', 'dplyr', 'tidyr', 'ggplot2', 'purrr', 'patchwork', 'jsonlite', 'covr', 'vdiffr', 'data.table'), repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v0.9.2/rClr_0.9.2.zip', repos = NULL, type = 'binary')"
  - Rscript -e "download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip?pr=false', destfile = 'ospsuite.zip', mode='wb'); install.packages('ospsuite.zip', repos = NULL, type = 'binary')"
  - Rscript -e "download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip?pr=false', destfile = 'ospsuite.utils.zip', mode='wb'); install.packages('ospsuite.utils.zip', repos = NULL, type = 'binary')"
  - Rscript -e "download.file('https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/tlf-library/artifacts/tlf.zip?pr=false', destfile = 'tlf.zip', mode='wb');  install.packages('tlf.zip', repos = NULL, type = 'binary')"
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl

before_test:
  - cinst pandoc
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v

on_success:
  - Rscript -e "covr::codecov(function_exclusions = c('print.*', '\\.onLoad'))"

after_test:
  - ps: copy ospsuite.parameteridentification_*.zip ospsuite.parameteridentification.zip

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: 'ospsuite.parameteridentification*.zip'
    name: Bits

platform: x64

skip_commits:
  files:
    - "*.md"

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - develop

pull_requests:
  do_not_increment_build_number: true
