name: main workflow

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  call-workflow:
    uses: Felixmil/Workflows/.github/workflows/R-CMD-check-build.yaml@v1
    with:
      RCLR_VERSION: 0.9.2
