name: pkgdown

on:
  push:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  pkgdown:
    uses: Felixmil/Workflows/.github/workflows/pkgdown.yaml@test-from-fork
    with:
      RCLR_VERSION: 0.9.2
