name: R-CMD-check-build

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  R-CMD-check-build:
    uses: Felixmil/Workflows/.github/workflows/R-CMD-check-build.yaml@test-from-fork
    with:
      RCLR_VERSION: 0.9.2
      extra-packages: "rClr=local::./rClr_${{ inputs.RCLR_VERSION }}.zip, ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils, tlf=github::Open-Systems-Pharmacology/TLF-Library, ospsuite=github::Open-Systems-Pharmacology/OSPSuite-R"
