name: test-pkg-and-coverage

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  test-pkg-and-coverage:
    uses: Felixmil/Workflows/.github/workflows/test-pkg-and-coverage.yaml@test-from-fork
    with:
      RCLR_VERSION: 0.9.2
