name: test-pkg-and-coverage

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  test-pkg-and-coverage:
    uses: Felixmil/Workflows/.github/workflows/test-pkg-and-coverage.yaml@test-from-fork
    with:
      RCLR_VERSION: 0.9.2
      extra-packages: |
        ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
        tlf=github::Open-Systems-Pharmacology/TLF-Library
        ospsuite=github::Open-Systems-Pharmacology/OSPSuite-R
